### ISSUE TITLE
Document how the TOC will make decisions

### ISSUE THREAD

**Issue by chipchilders** [cloudfoundry/community#15]
Perhaps:

Aim for consensus first, vote if no consensus possible in a reasonable timeframe.

How many votes are needed to make a decision in the affirmative?

**Comment by chipchilders** [comment]
@troytop says he has a good description of "consensus" somewhere

**Comment by bkrannich** [comment]
@chipchilders: Plus, there's the one one of my colleagues suggested for the bylaws: "Consensus is defined as the lack of sustained objection."

**Comment by troytop** [comment]
Turns out the document I was thinking of was not a description of consensus decision making, but a table of agreed terminology to use for group decisions. I can't attribute this properly because I don't remember where it comes from originally. 

Description | Term
-- | --
Best choice, cannot be improved upon | PERFECT
We all agree and support without reservation | CONSENSUS
The details may not be perfect, but it is close enough for me to support it here at the table and outside this meeting as well. | INFORMED CONSENT
I have reservations, I would like more discussion. I may then move up to consensus or informed consent; move down to concern; or agree that you can decide. I will not second-guess your decision outside this meeting. | RESERVATION
I have fundamental concerns; I am not able to support this choice at this time. | CONCERN
I do not agree, this is in conflict with my values and beliefs. | DISAGREEMENT
