### ISSUE TITLE
syslog-release owned by two WGs?

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/community#164]
Both the App Runtime Platform WG [here](https://github.com/cloudfoundry/community/blame/main/toc/working-groups/app-runtime-platform.md#L153) and the Foundational Infrastructure WG [here](https://github.com/cloudfoundry/community/blame/main/toc/working-groups/foundational-infrastructure.md#L174) list syslog-release as a repo that they own.

Is that by design?

**Comment by rkoster** [comment]
Don't think this was by design. At least don't remember any conversation about this during ToC meetings. Probably just an oversight.  Seems like the [last release was cut by tas-runtime-bot](https://github.com/cloudfoundry/syslog-release/releases/tag/v11.7.5). So maybe it makes sense to keep it in the App Runtime Platform working group.

**Comment by ctlong** [comment]
@rkoster that's not technically tied to the Application Runtime Platform working group. My understanding is that the repo is primarily being maintained by @Benjamintf1. Based off the conversation in the [CF slack thread](https://cloudfoundry.slack.com/archives/C02HNDJB31R/p1635961711015900?thread_ts=1635960086.015600&cid=C02HNDJB31R), my inclination is to remove this repo from the set of ARP repos and keep it in the Foundational Infrastructure working group.
