### ISSUE TITLE
TOC Candidate Nomination for Andy Hunt

### ISSUE THREAD

**Issue by LeePorte** [cloudfoundry/community#281]
Candidate Name: Andy Hunt

Affiliation: Government Digital Service (GOV.UK)

Nomination Statement: I’d like to nominate Andy Hunt, technical lead of the GOV.UK PaaS team. Andy is an active participant in the community particularly within the government space. His core focus is around maintaining the excellence of the end user experience, he has made several enhancements in this area and continues to engage in making things better for all of our end users. He is keen to see the community grow and move from strength to strength and has a desire to ensure that there is the right environment for this to happen.

**Comment by pburkholder** [comment]
I second this nomination. The U.S. cloud.gov team meets periodically with the GOV.UK PaaS team and I've been impressed with Andy's commitment to providing users with tooling and documentation.  Further, he's been a consistent contributor to upstream projects like UAA and the CF CLI.

The CF community as a whole benefits with public sector representation, and Andy would continue in that vein.

**Comment by emalm** [comment]
@LeePorte @pburkholder thanks for the nomination and the support!

@AP-Hunt, could you please reply or react with a 👍 to indicate that you accept the nomination?

**Comment by LeePorte** [comment]
Cheers for the ack @AP-Hunt

**Comment by emalm** [comment]
Since Andy's not currently an Approver or above in the governance role structure, @cloudfoundry/toc needs to approve the nomination as per section 7.e).i).(2) of the [CFF Charter](https://github.com/cloudfoundry/community/blob/main/governing-board/charter.md). TOC, please indicate your approval or objection via 👍 / 👎 reaction on this comment or reply on the discussion. Since this is urgent to resolve, let's interpret no reaction by noon PDT / 8 pm BST / 9 pm CEST as approval.
