### ISSUE TITLE
TOC Candidate Nomination for Peter Burkholder

### ISSUE THREAD

**Issue by LeePorte** [cloudfoundry/community#293]
Candidate Name: Peter Burkholder

Affiliation: Cloud.gov

Nomination Statement: I'd like to nominate Peter Burkholder who is Security and Compliance Lead of the cloud.gov team. Peter has been a key anchor within the public sector CF user space for a significant number of years, He is in regular contact with public sector CF operators and end users at a global level. He brings a security and compliance drive to CF, that has not previously been a focus of the technical side of the foundation. His recent focus has been on highlighting SBOMs and SLSA compliance to the TOC and how this could work across the different working groups.

**Comment by emalm** [comment]
@LeePorte thanks for the nomination!

@pburkholder, could you please reply or react with a 👍 to indicate that you accept the nomination? Thanks!

**Comment by pburkholder** [comment]
I accept!

**Comment by emalm** [comment]
Since Peter's not currently an Approver or above in the governance role structure, @cloudfoundry/toc needs to approve the nomination as per section 7.e).i).(2) of the [CFF Charter](https://github.com/cloudfoundry/community/blob/main/governing-board/charter.md). TOC, please indicate your approval or objection via 👍 / 👎 reaction on this comment or reply on the discussion. Since this is urgent to resolve, let's interpret no reaction by noon PDT / 8 pm BST / 9 pm CEST as approval. (Also, @LeePorte, I take your nomination as a pre-existing approval.)

**Comment by mogul** [comment]
Note there will be some caveats around Peter's participation, particularly around what happens if he leaves GSA (the org will want to replace him). GSA has some language in a letter being drafted.

**Comment by loewenstein** [comment]
I think the intention was that individuals are voted into the TOC, not organizations that are represented by individuals. I.e. he would keep his seat, or if he would step down, the TOC would decide on either taking the next candidate from a past vote or run a mid-term election.

**Comment by mogul** [comment]
Understood, and I'm pretty sure that's compatible with what's being drafted.

**Comment by emalm** [comment]
Closing as the 2022 TOC election has concluded.
